### ISSUE TITLE
Add a repository license.

### ISSUE THREAD

**Issue by DanielFL0** [binary-hideout/elecritic#1]
The current repository doesn't have a repository license. I suggest you take a look to the following link: https://choosealicense.com/ to select a license that fits your repository.

**Comment by netotz** [comment]
I like [GNU AGPLv3](https://choosealicense.com/licenses/agpl-3.0/), what do you think?

**Comment by DanielFL0** [comment]
[GNU AGPLv3](https://choosealicense.com/licenses/agpl-3.0/ ) seems fine to me.
